### ISSUE TITLE
V12 compatibility?

### ISSUE THREAD

**Issue by Damaskian** [philote/FoundryVTT-CthulhuDeepGreen#1]
Are there any plans to upgrade to Foundry V12? Thanks.

**Comment by philote** [comment]
It was tested and updated in v1.0.4 for Foundry V12
https://github.com/philote/cthulhudeepgreen/releases/tag/1.0.4

Are you experiencing an issue?

**Comment by Damaskian** [comment]
I was trying to make a roll with the character sheet in version 12.331 but it didn't work.

I think the problem was mine and not the system's, I reinstalled the foundry vtt and now I can make rolls.

Sorry for the inconvenience, it works fine!

**Comment by philote** [comment]
Glad to hear! No inconvenience at all.
